variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  image: ruby:2.3
  script:
  - mkdir events projects tech thoughts
  - mv pages/events.html events/index.html
  - mv pages/projects.html projects/index.html
  - mv pages/tech.html tech/index.html
  - mv pages/thoughts.html thoughts/index.html
  - mv blogposts/events/ _events/
  - mv blogposts/projects/ _projects
  - mv blogposts/tech/ _tech
  - mv blogposts/thoughts/ _thoughts
  - cp -R _tech/ _posts
  - cp -R _events/ _posts
  - cp -R _projects/ _posts
  - cp -R _thoughts/ _posts
  - rm -rf pages blogposts
  - bundle install
  - bundle exec jekyll build -d public
  - sed -i 's/Boris Budini – Boris Budini/Boris Budini/' public/index.html
  - sed -i 's/url(\/images\/Sidebar\/Tech\/router.jpg);\"><\/div>/url(\/images\/Sidebar\/index.jpg);\"><\/div>' public/index.html
  artifacts:
    paths:
    - public
  only:
  - master
