variables:
  JEKYLL_ENV: production

pages:
  image: kominoshja/jekyll-page:v1.1
  script:
  - bundle exec jekyll build -d public
  - sed -i 's/Boris Budini – Boris Budini/Boris Budini/' public/index.html
  - awk '/Boris Budini/{count++;if(count==3){sub("Boris Budini","Events")}}1' public/events-posts.html > public/newevent && mv public/newevent public/events-posts.html
  - sed -i 's/Kominoshja\x27s mindscape/Here\x27s what I\x27ve been attending lately./' public/events-posts.html

  artifacts:
    paths:
    - public
  only:
  - master
