variables:
  JEKYLL_ENV: production

pages:
  image: kominoshja/jekyll-page:v1.1
  script:
  - mkdir events projects tech thoughts
  - mv pages/events.html events/index.html
  - mv pages/projects.html projects/index.html
  - mv pages/tech.html tech/index.html
  - mv pages/thoughts.html thoughts/index.html
  - rm -rf pages
  - bundle exec jekyll build -d public
  - sed -i 's/Boris Budini – Boris Budini/Boris Budini/' public/index.html

  artifacts:
    paths:
    - public
  only:
  - master
