image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
- bundle install
- mkdir events projects tech thoughts
- mv pages/events.html events/index.html
- mv pages/projects.html projects/index.html
- mv pages/tech.html tech/index.html
- mv pages/thoughts.html thoughts/index.html
- rm -rf pages

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

