image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
- bundle install
- mkdir events projects tech thoughts
- mv pages/events.html events/index.html
- mv pages/projects.html projects/index.html
- mv pages/tech.html tech/index.html
- mv pages/thoughts.html thoughts/index.html
- mkdir _events  _projects  _tech  _thoughts
- cp -R blogposts/events/ _events/
- cp -R blogposts/projects/ _projects/
- cp -R blogposts/tech/ _tech/
- cp -R blogposts/thoughts/ _thoughts
- cp -R _tech/ _posts
- cp -R _events/ _posts
- cp -R _projects/ _posts
- cp -R _thoughts/ _posts
- rm -rf pages/ blogposts/

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

