title: Boris Budini
description: A website where I post my projects
url: https://boris.budini.xyz
site: Kominoshja's Mindscape
twitter:
  username: Kominoshja
social:
  name: Boris Budini
  links:
    - https://twitter.com/kominoshja
    - https://github.com/kominoshja
    - https://www.instagram.com/kominoshja
    - https://t.me/kominoshja

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /projects/:slug
  tech:
    output: true
    permalink: /tech/:slug
  events:
    output: true
    permalink: /events/:slug
  thoughts:
    output: true
    permalink: /thoughts/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "thoughts"
    values:
      layout: "thoughts"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "events"
  -
    scope:
      path: ""
      type: "tech"
    values:
      layout: "tech"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-twitter-plugin
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
paginate: 6
paginate_path: "/blog/page:num/"
