title: Boris Budini
description: DIY projects, system administration tips, broken code & more
url: https://boris.budini.xyz
site: Kominoshja's Mindscape


collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /projects/:slug
  tech:
    output: true
    permalink: /tech/:slug
  events:
    output: true
    permalink: /events/:slug
  thoughts:
    output: true
    permalink: /thoughts/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "thoughts"
    values:
      layout: "thoughts"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "events"
  -
    scope:
      path: ""
      type: "tech"
    values:
      layout: "tech"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

paginate: 6
paginate_path: "/blog/page:num/"
ajax_loading: false
algolia:
  application_id: 1KGN2Y8AB1  
  index_name: jekyll
  search_only_api_key: 5dbcbb19bce6bdedc84d7b8c7efafd7e
  files_to_exclude:
    - _data/*
    - _includes/*
    - _layouts/*
    - _pages/*
    - _sass/*
    - blogposts/*
    - css/*
    - js/*
    - index.html
    - 404.html
    - search.html
    - _posts/*
    - events/*
    - projects/*
    - tech/*
    - thoughts/*
